config/routes.rb
Rails.application.routes.draw do
  #use devise for user profiles
  devise_for :users
  #the "root" or home page can be found in the home in file in the pages folder
  root to: 'pages#home'
  #when a user is established bring up the profile
  resources :users do
  resource :profile
  end
  #for the about page find it in the about file in the pages folder
  get 'about', to: 'pages#about'
  #for the player page find it in the about file in the pages folder
  get 'player', to: 'pages#player'
  resources :contacts, only: :create
  #for the contact page find it in the about file in the pages folder
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
 end

app/models/application_record.rb
#SuperClass set up to be inherited in other classes
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
#In the contact form make sure there fields name, email, and comments are present
class Contact < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true
    validates :comments, presence: true
end

app/models/profile.rb
#profile is a subclass of user
class Profile < ActiveRecord::Base
     belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules and the user has a "profile". 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_one :profile
end

app/controllers/application_controller.rb
#security measurement taken by default in Ruby to mitigate multiple requests from the same client
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
#Contact form controls to assign fields and send message
class ContactsController < ApplicationController
  def new
   @contact = Contact.new
  end
  def create
    @contact = Contact.new(contact_params)
    #assign these fields the following parameters from the form and send message
    if @contact.save
        name = params[:contact][:name]
        email = params[:contact][:email]
        body = params[:contact][:comments]
        ContactMailer.contact_email(name, email, body).deliver
      #if message is successful send back message sent and redirect to contact form 
      flash[:success] = "Message sent."
       redirect_to new_contact_path
    else
       flash[:danger] = @contact.errors.full_messages.join(", ")
       redirect_to new_contact_path
    end
  end
  private
  def contact_params
     params.require(:contact).permit(:name, :email, :comments)
  end  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    def about
    end
    
    
end

app/controllers/profiles_controller.rb
#Create profile and assignit a user id requiring first name last name favorite artist and bio
class ProfilesController < ApplicationController
  
  def new
    @profile = Profile.new
  end
    def create
      # Make sure user is filling out form
      @user = User.find( params[:user_id] )
      # Profile linked to user
      @profile = @user.build_profile( profile_params )
      if @profile.save
        flash[:success] = "Profile Lit!"
        redirect_to user_path( params[:user_id] )
      else
        render action: :new
      end
    end
    private
         def profile_params
            params.require(:profile).permit(:first_name, :last_name, :fav_genre, :fav_artist, :bio)
         end
end

app/controllers/users_controller.rb
#find the user by the 'id' assigned to them in the database and show the user 
class UsersController < ApplicationController
  def show
    @user = User.find( params[:id] )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="container">
  <div class="row">
    <h2 class="text-center">Need Help?</h2>
    <div class="col-md-4 col-md-offset-4">
      <div class="well">
        <%-#Support ticket named under contact file to support devise gem formatting %>
        <%= form_for @contact do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :comments %>
            <%= f.text_area :comments, class: 'form-control' %>
          </div>
        <%-#Button given specific class for bootstrap formatting%>
          <%= f.submit 'Submit', class: 'btn btn-default' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<%-#Layout of the page in the application using bootstrap methodlogies-%>
<!DOCTYPE html>
<html>
  <head>
    <title>SoundzGood</title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css?family=Arimo:400,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <%-#Navigation bar-%>
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: "navbar-brand" do %>
            Home
          <% end %>
          <%= link_to about_path, class: "navbar-brand" do %>
            About Us
          <% end %>
          <%= link_to player_path, class: "navbar-brand" do %>
            Listen
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <div class="nav navbar-nav navbar-right">
            <%-#Links to pages-%>
            <%= link_to "Log In", new_user_session_path, class: "btn btn-default navbar-btn" %>
            <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-default navbar-btn" %>
            <%= link_to "Need Help?", new_contact_path, class: "btn btn-default navbar-btn" %>
            
          </div>
        </div><!-- /.navbar-collapse -->
        </div>
    </nav>
    <div class="container">
     <% flash.each do |type, msg| %>
      <%= content_tag :div, msg, class: "alert alert-#{type}" %>
    <% end %>
    </div> 
      <%= yield %>
    
    
  </body>
</html>

app/views/pages/about.html.erb
<div class="container text-center">
    <h1>About Us</h1>
    <p> SoundzGood is a streaming application unlike any other application available right now. </p>
    <p> This application was developed using a model for what users value in their streaming experience.</p>
    <p> This application promises to provide a new wave of experience for streaming digital music.</p>
</div>

app/views/pages/home.html.erb
<div class="home-callout text-center container-fluid">
  <h1>Welcome to SoundzGood</h1>
  <h2> The optimal streaming experience for every type of user!</h2>
  <p> Enjoy the streaming experience and create a profile to share interests with other users.</p>
 <%= link_to "Create your profile here!", (new_user_profile_path(user_id: current_user.id) if user_signed_in?), class: 'links' %>
</div>

app/views/pages/player.html.erb
<%-#music playing page-%>
<div class="container">
<h1> Listen to your favorite songs here! Plus many more inside!</h1>
<table class =" table-bordered table-hover">
        <thead class="thead-inverse">
            <tr class="active">
                <th><p>Song Title</p></th> 
                <th><p>Artist</p></th>
                <th><p>Length</p></th>
            </tr>
        </thead>
  
    <tbody>
            <%-#using the absolute reference to the files on the AWS server%>
        <tr>
            <td><p>Weary</p></td>
            <td><p>Solange</p></td>
            <td><%= audio_tag "https://s3-us-west-1.amazonaws.com/sitemusic/Music/02+Weary.m4a", controls: true%></td>
        </tr>
        <tr>
            <td><p>Brotha</p></td>
            <td><p>Angie Stone</p></td>
            <td><%= audio_tag "https://s3-us-west-1.amazonaws.com/sitemusic/Music/02+Brotha.m4a", controls: true%></td>
        </tr>
         <tr>
            <td><p>Work</p></td>
            <td><p>Rihanna ft. Drake</p></td>
            <td><%= audio_tag "https://s3-us-west-1.amazonaws.com/sitemusic/Music/01+Work+(feat.+Drake).m4a", controls: true%></td>
        </tr>
        <tr>
            <td><p>You Go Down Smooth</p></td>
            <td><p>Lake Street Drive</p></td>
            <td><%= audio_tag "https://s3-us-west-1.amazonaws.com/sitemusic/Music/05+You+Go+Down+Smooth.m4a", controls: true%></td>
        </tr>
        <tr>
            <td><p>Love Today</p></td>
            <td><p>Judith Hill</p></td>
            <td><%= audio_tag "https://s3-us-west-1.amazonaws.com/sitemusic/Music/01+Love+Today.m4a", controls: true%></td>
        </tr> 
        <tr>
            <td><p>Permission</p></td>
            <td><p>Ro James</p></td>
            <td><%= audio_tag "https://s3-us-west-1.amazonaws.com/sitemusic/Music/02+Permission.m4a", controls: true%></td>
        </tr>
        <tr>
            <td><p>Phone Down</p></td>
            <td><p>Erykah Badu</p></td>
            <td><%= audio_tag "https://s3-us-west-1.amazonaws.com/sitemusic/Music/04+Phone+Down.m4a", controls: true%></td>
        </tr>   
    </tbody>
</table>

</div>

app/views/profiles/_form.html.erb
<%-#Profile creation form-%>
<%= form_for @profile, url: user_profile_path do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :fav_artist %>
    <%= f.text_field :fav_artist, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :fav_genre %>
    <%= f.text_field :fav_genre, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :bio %>
    <%= f.text_area :bio, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Profile", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/profiles/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Create Your Profile</h1>
    <p class="text-center">Fill out your profile and interact with other music lovers!</p>
    <div class="well">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%-#Instructions on what to show for each user-%>
<div class="container">
<%= @user.inspect %>
<%= @user.profile.first_name %> <%= @user.profile.last_name %>
<%= @user.profile.fav_artist%>
<%= @user.profile.fav_genre%>
<%= @user.profile.bio %>
</div>